// ═══════════════════════════════════════════════════════════════
// Data Inspirasi Hidangan — 1000+ pilihan semua jenis
// Dipakai oleh halaman /inspirasi
// ═══════════════════════════════════════════════════════════════

export interface Dish {
  nama: string
  kategori: string
}

export const KATEGORI_EMOJI: Record<string, string> = {
  'Nasi': '🍚',
  'Mie & Bihun': '🍜',
  'Soto & Sup': '🍲',
  'Ayam & Bebek': '🍗',
  'Daging': '🥩',
  'Ikan & Seafood': '🐟',
  'Sayur': '🥬',
  'Tahu Tempe Telur': '🥚',
  'Sambal': '🌶️',
  'Sate': '🍢',
  'Khas Daerah': '🗺️',
  'Camilan & Gorengan': '🍟',
  'Kue Tradisional': '🍡',
  'Kue & Roti Modern': '🍰',
  'Dessert': '🍨',
  'Bubur & Sarapan': '🥣',
  'Minuman Tradisional': '🍹',
  'Kopi': '☕',
  'Teh & Minuman Segar': '🧋',
  'Internasional': '🌍',
  'Rumahan Sederhana': '🏠',
}

const RAW: Record<string, string[]> = {

  'Nasi': [
    'Nasi Goreng Kampung', 'Nasi Goreng Seafood', 'Nasi Goreng Ati Ampela', 'Nasi Goreng Pete',
    'Nasi Goreng Ikan Asin', 'Nasi Goreng Jawa', 'Nasi Goreng Hongkong', 'Nasi Goreng Teri Medan',
    'Nasi Goreng Kambing Kebon Sirih', 'Nasi Goreng Mawut', 'Nasi Goreng Babat', 'Nasi Goreng Kecombrang',
    'Nasi Uduk Betawi', 'Nasi Kuning', 'Nasi Liwet Solo', 'Nasi Liwet Sunda', 'Nasi Kebuli',
    'Nasi Mandhi', 'Nasi Briyani Ayam', 'Nasi Ulam', 'Nasi Bakar Ayam Kemangi', 'Nasi Bakar Teri',
    'Nasi Bakar Cumi Pedas', 'Nasi Bakar Jamur', 'Nasi Pecel Madiun', 'Nasi Campur Bali',
    'Nasi Jinggo', 'Nasi Krawu Gresik', 'Nasi Boranan Lamongan', 'Nasi Gandul Pati',
    'Nasi Megono Pekalongan', 'Nasi Grombyang Pemalang', 'Nasi Jamblang Cirebon', 'Nasi Lengko Cirebon',
    'Nasi Timbel Sunda', 'Nasi Tutug Oncom', 'Nasi Kucing Angkringan', 'Nasi Ayam Hainan',
    'Nasi Tim Ayam', 'Nasi Kapau', 'Nasi Rames Komplit', 'Nasi Langgi Solo',
    'Nasi Minyak Palembang', 'Nasi Gurih Aceh', 'Nasi Serpang Madura', 'Nasi Tempong Banyuwangi',
  ],

  'Mie & Bihun': [
    'Mie Goreng Jawa', 'Mie Ayam Bakso', 'Mie Ayam Jamur', 'Mie Ayam Wonogiri', 'Mie Ayam Ceker',
    'Mie Aceh Goreng', 'Mie Aceh Kuah', 'Mie Celor Palembang', 'Mie Koclok Cirebon',
    'Mie Kocok Bandung', 'Mie Ongklok Wonosobo', 'Mie Cakalang Manado', 'Mie Titi Makassar',
    'Mie Gomak Batak', 'Mie Lethek Bantul', 'Mie Kangkung', 'Mie Tarempa Kepri',
    'Mie Rebus Medan', 'Mie Tektek', 'Mie Nyemek', 'Mie Godog Jawa', 'Ifumie Goreng Seafood',
    'Kwetiau Goreng Sapi', 'Kwetiau Siram Seafood', 'Bihun Goreng Spesial', 'Bihun Kuah Ayam',
    'Misoa Kuah Udang', 'Laksa Bogor', 'Laksa Betawi', 'Laksa Medan', 'Mie Bangka',
    'Mie Kering Makassar', 'Lomie Jakarta', 'Cwie Mie Malang', 'Mie Yamin Manis',
    'Mie Pangsit Ayam', 'Soun Goreng Udang', 'Mie Sagu Riau', 'Mie Glosor Bogor',
    'Mie Kopyok Semarang', 'Mie Sop Medan', 'Mie Instan Goreng Telur Keju', 'Mie Kuah Pedas Korea',
    'Spaghetti Goreng Kampung',
  ],

  'Soto & Sup': [
    'Soto Betawi', 'Soto Madura', 'Soto Lamongan', 'Soto Kudus', 'Soto Banjar', 'Soto Padang',
    'Soto Bandung', 'Soto Sokaraja', 'Soto Mie Bogor', 'Soto Tangkar', 'Soto Ayam Ambengan',
    'Soto Daging Sapi', 'Soto Babat', 'Tauto Pekalongan', 'Coto Makassar', 'Sroto Purwokerto',
    'Soto Kemiri Pati', 'Soto Seger Boyolali', 'Soto Bathok', 'Soto Ceker',
    'Sup Ayam Kampung', 'Sup Buntut', 'Sup Buntut Bakar', 'Sup Iga Sapi', 'Sup Kaki Kambing',
    'Sup Matahari Solo', 'Sup Konro Makassar', 'Sup Brenebon Manado', 'Sup Jagung Ayam',
    'Sup Krim Jamur', 'Sup Tomat Bakso', 'Sup Makaroni Ayam', 'Sup Kimlo', 'Sup Bening Bayam Jagung',
    'Sayur Sop Sederhana', 'Tekwan Palembang', 'Bakso Malang Komplit', 'Bakso Aci Tulang Rangu',
    'Bakso Urat Jumbo', 'Bakso Beranak', 'Bakso Mercon', 'Rawon Surabaya', 'Timlo Solo',
    'Garang Asem Ayam', 'Sup Ikan Batam', 'Pindang Patin Palembang', 'Pindang Tulang',
    'Pindang Serani Jepara', 'Empal Gentong Cirebon', 'Sup Kepala Ikan Kakap',
    'Lontong Cap Go Meh', 'Lontong Sayur Medan', 'Sup Oyong Misoa', 'Sup Ceker Pedas',
    'Sup Labu Kuning', 'Tengkleng Solo',
  ],

  'Ayam & Bebek': [
    'Ayam Goreng Lengkuas', 'Ayam Goreng Kremes', 'Ayam Goreng Kalasan', 'Ayam Goreng Lalapan',
    'Ayam Goreng Mentega', 'Ayam Goreng Tepung Crispy', 'Ayam Bakar Taliwang', 'Ayam Bakar Padang',
    'Ayam Bakar Kecap', 'Ayam Bakar Bumbu Rujak', 'Ayam Bakar Madu', 'Ayam Bakar Bumbu Bali',
    'Ayam Panggang Klaten', 'Ayam Panggang Oven Madu', 'Ayam Betutu Bali', 'Ayam Rica-Rica',
    'Ayam Woku Belanga', 'Ayam Pop Padang', 'Ayam Gulai Kapau', 'Ayam Balado', 'Ayam Geprek Sambal Korek',
    'Ayam Geprek Mozarella', 'Ayam Penyet Surabaya', 'Ayam Cabe Ijo', 'Ayam Suwir Kemangi',
    'Ayam Sisit Bali', 'Ayam Kecap Mentega', 'Ayam Saus Padang', 'Ayam Saus Tiram',
    'Ayam Asam Manis', 'Ayam Teriyaki', 'Ayam Katsu', 'Ayam Serundeng', 'Ayam Lodho Tulungagung',
    'Ayam Ingkung Jawa', 'Ayam Tangkap Aceh', 'Ayam Masak Habang Banjar', 'Ayam Cincane Samarinda',
    'Ayam Garo Rica', 'Opor Ayam Kuning', 'Opor Ayam Putih', 'Semur Ayam Kentang',
    'Kari Ayam Jawa', 'Ayam Kungpao', 'Ayam Cabai Garam', 'Sayap Ayam Pedas Manis',
    'Ceker Ayam Pedas', 'Ceker Mercon', 'Ati Ampela Goreng Bumbu', 'Ayam Kodok Betawi',
    'Ayam Pelalah Lombok', 'Ayam Masak Merah', 'Ayam Bistik', 'Ayam Suwir Pedas Daun Jeruk',
    'Ayam Rebus Jahe', 'Ayam Panggang Rica', 'Bebek Goreng Kremes', 'Bebek Bakar Madura',
    'Bebek Betutu', 'Bebek Peking', 'Bebek Rica-Rica', 'Bebek Songkem Madura', 'Bebek Sinjay',
    'Bebek Goreng Sambal Ijo', 'Ayam Goreng Bawang Putih',
  ],

  'Daging': [
    'Rendang Daging Sapi', 'Rendang Ayam', 'Rendang Jengkol', 'Rendang Paru', 'Rendang Telur',
    'Semur Daging Betawi', 'Semur Jengkol', 'Empal Gepuk Sunda', 'Dendeng Balado',
    'Dendeng Batokok', 'Dendeng Ragi', 'Krengsengan Daging', 'Tongseng Kambing', 'Tongseng Sapi',
    'Gulai Kambing', 'Gule Sapi Jawa', 'Kalio Daging', 'Sapi Lada Hitam', 'Daging Masak Kecap',
    'Rolade Daging Sapi', 'Bistik Daging Jawa', 'Selat Solo', 'Malbi Daging Palembang',
    'Se\'i Sapi Kupang', 'Tumis Daging Cabai Hijau', 'Abon Sapi Manis', 'Kornet Goreng Telur',
    'Iga Bakar Kecap', 'Iga Penyet Sambal Terasi', 'Konro Bakar', 'Sop Sumsum Langsa',
    'Oseng Mercon Daging', 'Daging Sapi Teriyaki', 'Daging Gepuk Manis', 'Kikil Balado',
    'Sambal Goreng Ati Kentang', 'Paru Goreng Kering', 'Babat Gongso Semarang', 'Empal Daging Serundeng',
    'Asam Padeh Daging', 'Itiak Lado Mudo', 'Kambing Guling', 'Sate Goreng Sapi',
    'Daging Bumbu Bali', 'Lapis Daging Surabaya', 'Daging Cincang Kentang', 'Tumis Kikil Cabe Ijo',
    'Sop Kikil', 'Tumis Daging Sapi Pete', 'Daging Sapi Saus Tiram', 'Buntut Goreng Sambal Kecap',
  ],

  'Ikan & Seafood': [
    'Ikan Bakar Jimbaran', 'Ikan Bakar Manokwari', 'Ikan Bakar Rica', 'Ikan Bakar Colo-Colo',
    'Gurame Goreng Terbang', 'Gurame Asam Manis', 'Gurame Bakar Kecap', 'Gurame Saus Padang',
    'Pecel Lele Lamongan', 'Mangut Lele', 'Mangut Ikan Pari Asap', 'Ikan Woku Belanga',
    'Ikan Kuah Kuning Papua', 'Arsik Ikan Mas', 'Naniura Batak', 'Ikan Mas Bumbu Kuning',
    'Pepes Ikan Mas', 'Pepes Teri Jengki', 'Pepes Udang Kemangi', 'Asam Padeh Ikan Tongkol',
    'Gulai Ikan Kakap', 'Kakap Saus Padang', 'Kerapu Steam Hongkong', 'Bandeng Presto',
    'Bandeng Bakar Tanpa Duri', 'Otak-Otak Bandeng', 'Sate Bandeng Banten', 'Cakalang Fufu Manado',
    'Cakalang Rica Suwir', 'Tuna Sambal Matah', 'Tuna Bakar Dabu-Dabu', 'Cumi Saus Padang',
    'Cumi Hitam Kecap', 'Cumi Goreng Tepung Krispi', 'Cumi Bakar Madu', 'Cumi Cabai Garam',
    'Udang Balado', 'Udang Saus Tiram', 'Udang Asam Manis', 'Udang Goreng Mentega',
    'Udang Bakar Jimbaran', 'Udang Saus Padang', 'Udang Selingkuh Wamena', 'Kepiting Saus Padang',
    'Kepiting Asap', 'Kepiting Soka Goreng Tepung', 'Kerang Ijo Saus Padang', 'Kerang Dara Rebus Sambal',
    'Ikan Asin Sepat Sambal', 'Peda Merah Sambal Pete', 'Teri Kacang Balado', 'Sarden Tomat Pedas',
    'Pallumara Makassar', 'Gohu Ikan Ternate', 'Ikan Tude Bakar', 'Botok Teri Pete Cina',
    'Pindang Bandeng Tetel', 'Siomay Ikan Bandung', 'Pesmol Ikan Nila', 'Nila Bakar Sambal Kecap',
    'Salmon Panggang Teriyaki', 'Dori Goreng Tepung Saus Asam Manis', 'Fish and Chips',
    'Lele Bumbu Mangut Pedas', 'Kepala Kakap Kuah Asam',
  ],

  'Sayur': [
    'Sayur Asem Jakarta', 'Sayur Asem Sunda', 'Sayur Lodeh Jawa', 'Sayur Bening Bayam',
    'Sayur Bobor Bayam', 'Sayur Besan Betawi', 'Gulai Daun Singkong', 'Gulai Nangka Muda',
    'Gulai Pakis', 'Sayur Nangka Gudeg', 'Tumis Kangkung Terasi', 'Cah Kangkung Bawang Putih',
    'Plecing Kangkung Lombok', 'Tumis Buncis Udang', 'Tumis Tauge Ikan Asin', 'Tumis Genjer Oncom',
    'Tumis Pare Teri', 'Tumis Jamur Tiram Pedas', 'Tumis Labu Siam', 'Orak-Arik Buncis Telur',
    'Capcay Goreng', 'Capcay Kuah Seafood', 'Brokoli Cah Bawang Putih', 'Terong Balado',
    'Terong Penyet Sambal Terasi', 'Terong Raos Crispy', 'Sambal Goreng Kentang Ati',
    'Kering Kentang Teri Kacang', 'Perkedel Kentang', 'Perkedel Jagung Manado', 'Urap Sayur Jawa',
    'Trancam Solo', 'Gudangan Jawa', 'Pecel Sayur Komplit', 'Karedok Sunda', 'Lotek Bandung',
    'Asinan Betawi', 'Asinan Bogor', 'Lawar Bali', 'Anyang Pakis Melayu', 'Buntil Daun Pepaya',
    'Botok Tempe Lamtoro', 'Oseng Daun Pepaya Teri', 'Tumis Bunga Pepaya Cakalang',
    'Sayur Rebung Santan', 'Lodeh Kluwih', 'Brongkos Yogyakarta', 'Krecek Sambal Goreng',
    'Acar Kuning Sayuran', 'Acar Timun Wortel', 'Sayur Ketupat Betawi', 'Sayur Labu Kuning Santan',
    'Cah Pokcoy Jamur', 'Salad Sayur Saus Wijen', 'Tumis Kacang Panjang Tempe',
    'Oseng Kikil Daun Jeruk', 'Cah Sawi Putih Bakso', 'Tumis Kembang Kol Sosis',
    'Sayur Bayam Jagung Manis', 'Oseng Pepaya Muda',
  ],

  'Tahu Tempe Telur': [
    'Tempe Orek Basah', 'Tempe Orek Kering', 'Tempe Mendoan Banyumas', 'Tempe Bacem',
    'Tahu Bacem', 'Tempe Penyet', 'Tahu Gejrot Cirebon', 'Tahu Sumedang', 'Tahu Walik Banyuwangi',
    'Tahu Bakso Ungaran', 'Tahu Isi Sayur', 'Tahu Crispy Cabai Garam', 'Tahu Telur Surabaya',
    'Tahu Tek Surabaya', 'Kupat Tahu Magelang', 'Tahu Gimbal Semarang', 'Tahu Campur Lamongan',
    'Tahu Fantasi Kukus', 'Steak Tempe', 'Tempe Goreng Tepung', 'Kering Tempe Kacang Teri',
    'Sambal Goreng Tempe Pete', 'Tumis Tempe Kecap Pedas', 'Botok Tahu Tempe Teri',
    'Pepes Tahu Kemangi', 'Semur Tahu Telur', 'Tahu Kecap Cabai Hijau', 'Tahu Cabe Garam',
    'Telur Balado', 'Telur Dadar Padang', 'Telur Ceplok Sambal Kecap', 'Semur Telur Betawi',
    'Telur Pindang Jawa', 'Telur Asin Goreng Sambal', 'Sambal Telur Puyuh Kentang',
    'Omelet Sayur Keju', 'Orak-Arik Telur Tomat', 'Telur Gulung Jajanan', 'Telur Dadar Krispi Padang',
    'Tahu Kukus Telur Asin', 'Oseng Tahu Tauge', 'Tempe Kemul Wonosobo', 'Perkedel Tahu',
    'Egg Roll Tahu Ayam',
  ],

  'Sambal': [
    'Sambal Terasi Mentah', 'Sambal Terasi Matang', 'Sambal Bawang', 'Sambal Matah Bali',
    'Sambal Ijo Padang', 'Sambal Dabu-Dabu Manado', 'Sambal Korek', 'Sambal Bajak Jawa',
    'Sambal Kecap Rawit', 'Sambal Tomat', 'Sambal Pecel Madiun', 'Sambal Kacang Sate',
    'Sambal Roa Manado', 'Sambal Andaliman Batak', 'Sambal Tempoyak Jambi', 'Sambal Mangga Muda',
    'Sambal Kemangi', 'Sambal Pete Udang', 'Sambal Teri Medan', 'Sambal Cumi Asin',
    'Sambal Geprek', 'Sambal Embe Bali', 'Sambal Luat Kupang', 'Sambal Kandas Sarai Dayak',
    'Sambal Gandaria Betawi', 'Sambal Rica Manado', 'Sambal Colo-Colo Ambon', 'Sambal Honje Sunda',
    'Sambal Serai Pedas', 'Sambal Belimbing Wuluh', 'Sambal Goreng Krecek', 'Sambal Terong Teri',
    'Sambal Ebi Pedas', 'Sambal Jeruk Limau', 'Sambal Bongkot',
  ],

  'Sate': [
    'Sate Ayam Madura', 'Sate Kambing Bumbu Kecap', 'Sate Maranggi Purwakarta', 'Sate Padang',
    'Sate Lilit Bali', 'Sate Klathak Bantul', 'Sate Buntel Solo', 'Sate Taichan',
    'Sate Kerang Surabaya', 'Sate Usus Angkringan', 'Sate Kulit Ayam', 'Sate Telur Puyuh',
    'Sate Banjar', 'Sate Rembiga Lombok', 'Sate Ambal Kebumen', 'Sate Blora', 'Sate Ponorogo',
    'Sate Tegal Balibul', 'Sate Matang Aceh', 'Sate Kere Solo', 'Sate Jamur Tiram',
    'Sate Tempe Bumbu Kacang', 'Sate Sapi Manis', 'Sate Udang Bakar Madu', 'Sate Cumi Pedas',
    'Sate Bebek Tambak', 'Sate Pusut Lombok', 'Sate Loso Pemalang', 'Sate Kikil Kecap',
    'Sate Ati Ampela',
  ],

  'Khas Daerah': [
    'Gudeg Jogja Komplit', 'Gudeg Manggar', 'Papeda Kuah Kuning', 'Pempek Kapal Selam',
    'Pempek Lenjer', 'Pempek Adaan', 'Pempek Kulit', 'Pempek Pistel', 'Model Palembang',
    'Celimpungan Palembang', 'Laksan Palembang', 'Burgo Palembang', 'Ragit Palembang',
    'Gado-Gado Jakarta', 'Ketoprak Jakarta', 'Kerak Telor Betawi', 'Gabus Pucung Betawi',
    'Sayur Godog Betawi', 'Batagor Bandung', 'Siomay Bandung Komplit', 'Cireng Isi Ayam Pedas',
    'Cilok Bumbu Kacang', 'Cimol Bojot', 'Seblak Ceker Pedas', 'Seblak Komplit Bandung',
    'Lumpia Semarang', 'Tahu Pong Semarang', 'Rujak Soto Banyuwangi', 'Sego Tempong',
    'Pecel Rawon Banyuwangi', 'Lontong Balap Surabaya', 'Rujak Cingur Surabaya',
    'Rujak Petis Madura', 'Bebek Songkem', 'Kaledo Palu', 'Binte Biluhuta Gorontalo',
    'Ilabulo Gorontalo', 'Tinutuan Manado', 'Ayam Tuturuga', 'Panada Manado', 'Klappertaart Manado',
    'Natinombur Batak', 'Dekke Naniarsik', 'Ayam Napinadar', 'Mie Gomak Kuah', 'Lappet Batak',
    'Ombus-Ombus', 'Bika Ambon Medan', 'Lontong Medan', 'Soto Medan', 'Anyang Ayam Medan',
    'Gulai Belacan Riau', 'Asam Pedas Baung Riau', 'Otak-Otak Batam', 'Luti Gendang Kepri',
    'Tempoyak Ikan Patin', 'Pendap Bengkulu', 'Bagar Hiu Bengkulu', 'Seruit Lampung',
    'Gulai Taboh Lampung', 'Mie Belitung', 'Gangan Ikan Belitung', 'Lempah Kuning Bangka',
    'Martabak Bangka', 'Rusip Bangka', 'Kue Rintak Bangka', 'Ayam Taliwang Lombok',
    'Sayur Ares Lombok', 'Bebalung Lombok', 'Karmanaci Timor', 'Jagung Bose NTT',
    'Kolo Nasi Bakar NTT', 'Catemak Jagung', 'Juku Pallumara', 'Barongko Bugis',
    'Kapurung Palopo', 'Burasa Makassar', 'Songkolo Bagadang', 'Jalangkote Makassar',
    'Pisang Epe Makassar', 'Pallubasa Makassar', 'Ayam Nasu Palekko', 'Soppeng Nasu Likku',
    'Sinonggi Kendari', 'Kasoami Buton', 'Lapa-Lapa Buton', 'Woku Komo-Komo',
    'Gohu Ternate', 'Halua Kenari Maluku', 'Nasi Lapola Ambon', 'Kohu-Kohu Ambon',
    'Sagu Lempeng Papua', 'Udang Selingkuh Papua', 'Aunu Senebre Papua', 'Ikan Bungkus Papua',
    'Juhu Singkah Dayak', 'Wadi Ikan Kalimantan', 'Ayam Cincane', 'Sate Payau Kaltim',
    'Gence Ruan Kaltim', 'Ketupat Kandangan', 'Gangan Asam Banjar', 'Ipau Banjar',
    'Amparan Tatak Banjar', 'Bingka Banjar', 'Soto Kuin Banjarmasin', 'Manday Kalimantan',
    'Pengkang Pontianak', 'Bubur Pedas Sambas', 'Chai Kwe Pontianak', 'Sotong Pangkong',
    'Mie Sagu Selatpanjang', 'Roti Canai Aceh', 'Kuah Pliek U Aceh', 'Sie Reuboh Aceh',
    'Kuah Beulangong', 'Timphan Aceh', 'Eungkot Paya Aceh', 'Gulai Kepala Ikan Padang',
    'Sate Danguang-Danguang', 'Palai Rinuak Maninjau', 'Randang Lokan', 'Gulai Itiak Koto Gadang',
    'Lamang Tapai', 'Galamai Payakumbuh',
  ],

  'Camilan & Gorengan': [
    'Bakwan Sayur', 'Bakwan Jagung', 'Bakwan Udang', 'Pisang Goreng Crispy', 'Pisang Goreng Madu',
    'Pisang Molen', 'Pisang Nugget', 'Pisang Coklat Lumer', 'Tahu Isi Pedas', 'Tempe Kemul',
    'Cireng Bumbu Rujak', 'Cilung', 'Cilor', 'Basreng Pedas Daun Jeruk', 'Makaroni Ngehe',
    'Keripik Kaca', 'Keripik Singkong Balado', 'Keripik Pisang Coklat', 'Keripik Tempe Sagu',
    'Keripik Bayam', 'Keripik Usus', 'Keripik Ceker', 'Kerupuk Kulit', 'Rempeyek Kacang',
    'Rempeyek Teri', 'Rempeyek Rebon', 'Rengginang Terasi', 'Opak Singkong', 'Emping Melinjo',
    'Sukun Goreng', 'Ubi Goreng Wijen', 'Singkong Goreng Keju', 'Singkong Thailand',
    'Combro', 'Misro', 'Gehu Pedas', 'Otak-Otak Goreng', 'Sempol Ayam', 'Sostel Sosis Telur',
    'Corndog Mozarella', 'Piscok Crispy', 'Roti Goreng Isi Ayam', 'Risoles Ragout',
    'Risoles Mayo Smoked Beef', 'Pastel Isi Bihun', 'Kroket Kentang', 'Lemper Ayam',
    'Lemper Bakar', 'Arem-Arem', 'Semar Mendem', 'Lumpia Goreng Rebung', 'Lumpia Basah Bandung',
    'Martabak Telur', 'Martabak Mini Kari', 'Molring Crispy', 'Cimin', 'Cilok Goang',
    'Batagor Kering', 'Tahu Gejrot Pedas', 'Donat Kentang Mini', 'Roti Bakar Coklat Keju',
    'Roti Maryam Coklat', 'Pukis Keju', 'Telur Gulung Sosis', 'Papeda Telur Gulung',
    'Kebab Mini Goreng', 'Samosa Kentang', 'Tempura Sayur', 'Onion Ring Crispy',
    'French Fries Bumbu Balado', 'Potato Wedges Keju', 'Nachos Saus Keju', 'Popcorn Caramel',
    'Jasuke Jagung Susu Keju',
  ],

  'Kue Tradisional': [
    'Klepon Pandan', 'Onde-Onde Kacang Hijau', 'Onde-Onde Ketawa', 'Getuk Lindri', 'Getuk Goreng Sokaraja',
    'Cenil Kenyal', 'Lupis Ketan', 'Tiwul Gunungkidul', 'Gatot Singkong', 'Sawut Singkong',
    'Serabi Solo', 'Serabi Bandung Oncom', 'Surabi Kinca', 'Kue Cucur Gula Merah', 'Kue Lapis Sagu',
    'Lapis Legit', 'Lapis Surabaya', 'Kue Putu Bambu', 'Putu Ayu Pandan', 'Putu Mayang',
    'Nagasari Pisang', 'Kue Talam Pandan', 'Talam Ubi Ungu', 'Kue Ku Merah', 'Wajik Ketan Gula Merah',
    'Jadah Tempe Kaliurang', 'Jenang Grendul', 'Jenang Sumsum', 'Dadar Gulung Kelapa',
    'Kue Lumpur Kentang', 'Kue Lumpur Labu', 'Bika Ambon', 'Bolu Kukus Mekar', 'Bolu Gulung Pandan',
    'Apem Selong', 'Apem Kukus Gula Merah', 'Kue Pancong', 'Kue Rangi Betawi', 'Kue Ape Jakarta',
    'Kue Cubit Setengah Matang', 'Kue Pukis Pandan', 'Bandros Sunda', 'Carabikang Mekar',
    'Kue Mangkok Tape', 'Kue Bugis Ketan Hitam', 'Kue Lumpang Pandan', 'Kue 8 Jam Palembang',
    'Maksuba Palembang', 'Engkak Ketan', 'Kue Sagon Kelapa', 'Kue Satu Kacang Hijau',
    'Kembang Goyang', 'Akar Kelapa Betawi', 'Kue Gapit', 'Kue Semprong', 'Kue Sagu Keju',
    'Nastar Nanas', 'Kastengel Keju', 'Putri Salju', 'Lidah Kucing', 'Kue Kacang Tanah',
    'Wingko Babat', 'Moci Sukabumi', 'Dodol Garut', 'Dodol Betawi', 'Jenang Kudus',
    'Geplak Bantul', 'Yangko Yogyakarta', 'Bakpia Pathok', 'Bakpia Kukus Coklat', 'Pia Legong Bali',
    'Kue Bulan', 'Bapel Wonosobo', 'Kue Leker Solo', 'Kue Gandos', 'Rondo Royal Tape Goreng',
    'Grontol Jagung', 'Horog-Horog Jepara', 'Awug Beras Sunda', 'Kue Clorot Purworejo',
    'Kue Dumbeg', 'Legomoro Kotagede', 'Kipo Kotagede', 'Madu Mongso', 'Wingko Kelapa Muda',
    'Kue Cente Manis', 'Sengkulun', 'Kue Pepe Betawi', 'Kue Talam Ebi', 'Lapek Bugih Minang',
    'Kue Putri Mandi', 'Ongol-Ongol Sagu', 'Cantik Manis Hunkwe', 'Kue Lumpang Ebi',
    'Bolu Kemojo Riau', 'Kue Bingke Pontianak', 'Kue Bangkit Sagu', 'Kue Asida Maluku',
  ],

  'Kue & Roti Modern': [
    'Brownies Panggang Fudgy', 'Brownies Kukus Coklat', 'Bolu Pandan Santan', 'Bolu Jadul Keju',
    'Bolu Tape Keju', 'Bolu Pisang Coklat', 'Chiffon Cake Pandan', 'Sponge Cake Vanilla',
    'Red Velvet Cake', 'Cheesecake Lumer', 'Japanese Cheesecake', 'Tiramisu Cake',
    'Black Forest', 'Rainbow Cake', 'Ogura Cake Keju', 'Castella Cake', 'Marmer Cake Jadul',
    'Butter Cookies', 'Choco Chip Cookies', 'Soft Cookies Coklat Lumer', 'Palm Cheese Cookies',
    'Cromboloni Coklat', 'Croissant Butter', 'Cinnamon Roll', 'Roti Sobek Coklat',
    'Roti Gembong Gedhe', 'Roti Boy Kopi', 'Roti Unyil Bogor', 'Roti Kukus Srikaya',
    'Donat Gula Halus', 'Donat Glaze Coklat', 'Donat Bomboloni', 'Milk Bun Thailand',
    'Korean Garlic Bread', 'Cupcake Red Velvet', 'Muffin Coklat Chip', 'Banana Bread Panggang',
    'Pound Cake Lemon', 'Brownies Lumer Skotel', 'Roll Cake Matcha', 'Pastel Tutup Panggang',
    'Pie Susu Bali', 'Egg Tart Portugis', 'Klapertart Kenari', 'Pandan Crepe Cake',
    'Mille Crepes Coklat', 'Dorayaki Coklat', 'Pancake Fluffy Madu', 'Waffle Coklat Keju',
    'Churros Saus Coklat', 'Kue Balok Lumer',
  ],

  'Dessert': [
    'Es Krim Goreng', 'Es Krim Vanilla Homemade', 'Es Krim Coklat', 'Gelato Pistachio',
    'Puding Coklat Vla Vanilla', 'Puding Busa Strawberry', 'Puding Roti Panggang', 'Puding Sutra Mangga',
    'Silky Puding Taro', 'Panna Cotta Berry', 'Creme Brulee', 'Flan Karamel',
    'Mousse Coklat', 'Tiramisu Cup', 'Banana Split', 'Banoffee Cup', 'Fruit Sando Jepang',
    'Choux Cream Sus', 'Kue Sus Vla Durian', 'Profiteroles Coklat', 'Eclair Coklat',
    'Macaron Perancis', 'Creme Puff', 'Mochi Es Krim', 'Mochi Daifuku Kacang Merah',
    'Dango Jepang', 'Bingsu Mangga', 'Bingsu Coklat Oreo', 'Es Campur Spesial', 'Es Teler',
    'Es Doger Bandung', 'Es Pisang Ijo Makassar', 'Es Palu Butung', 'Es Cendol Dawet',
    'Es Dawet Ayu Banjarnegara', 'Es Podeng', 'Es Goyobod Garut', 'Es Oyen Bandung',
    'Es Kuwut Bali', 'Es Selendang Mayang', 'Es Sekoteng Singapore', 'Kolak Pisang Ubi',
    'Kolak Biji Salak', 'Bubur Kacang Hijau Ketan Hitam', 'Bubur Candil Ubi', 'Sarikaya Roti Tawar',
    'Pisang Ijo Vla', 'Sop Buah Segar', 'Salad Buah Yogurt Keju', 'Regal Dessert Box',
    'Dessert Box Coklat Lumer', 'Mango Sticky Rice',
  ],

  'Bubur & Sarapan': [
    'Bubur Ayam Jakarta', 'Bubur Ayam Cianjur', 'Bubur Ayam Sukabumi', 'Bubur Manado Tinutuan',
    'Bubur Ase Betawi', 'Bubur Sumsum Gula Merah', 'Bubur Ketan Hitam', 'Bubur Kacang Hijau Santan',
    'Bubur Candil', 'Bubur Jagung Manis', 'Bubur Sagu Ambon', 'Bubur Pedas Melayu',
    'Bubur Suro Jawa', 'Bubur Lemu Solo', 'Nasi Tim Ayam Jamur', 'Bubur Polenta Jagung',
    'Oatmeal Pisang Madu', 'Overnight Oats Coklat', 'Granola Yogurt Bowl', 'Smoothie Bowl Mangga',
    'Roti Bakar Telur Keju', 'Sandwich Telur Mayo', 'Roti Panggang Alpukat', 'French Toast Madu',
    'Pancake Pisang Simple', 'Telur Setengah Matang Roti', 'Nasi Goreng Pagi Simple',
    'Lontong Sayur Betawi', 'Ketupat Sayur Padang', 'Nasi Kuning Sarapan', 'Sego Godog',
    'Nasi Krawu Sarapan', 'Bubur Ayam Kuah Kuning',
  ],

  'Minuman Tradisional': [
    'Wedang Jahe Gula Merah', 'Wedang Ronde Jahe', 'Wedang Uwuh Imogiri', 'Wedang Secang',
    'Wedang Angsle Malang', 'Wedang Kacang Tanah', 'Bajigur Sunda', 'Bandrek Panas',
    'Sekoteng Jakarta', 'Bir Pletok Betawi', 'STMJ Susu Telur Madu Jahe', 'Jamu Kunyit Asam',
    'Jamu Beras Kencur', 'Jamu Temulawak', 'Jamu Galian Singset', 'Wedang Serbat Kayu Manis',
    'Es Cincau Hijau Santan', 'Es Cincau Hitam Gula Merah', 'Es Cendol Elizabeth', 'Dawet Ireng Purworejo',
    'Es Legen Tuban', 'Es Temulawak Jawa', 'Loloh Cemcem Bali', 'Es Daluman Bali',
    'Sarabba Makassar', 'Es Sirap Bandung Merah', 'Es Timun Suri Sirup', 'Es Blewah Gula Aren',
    'Es Kelapa Muda Jeruk', 'Es Kelapa Kopyor', 'Es Cingcau Susu', 'Air Guraka Ternate',
    'Kopi Rarobang Ambon', 'Wedang Pokak Probolinggo', 'Beer Kotjok Bogor', 'Wedang Coro Pati',
    'Es Air Mata Pengantin', 'Lahang Aren Segar', 'Cendol Duren',
  ],

  'Kopi': [
    'Kopi Tubruk Jawa', 'Kopi Susu Gula Aren', 'Es Kopi Susu Kekinian', 'Kopi Joss Arang Jogja',
    'Kopi Klotok Pakem', 'Kopi Talua Padang', 'Kopi Sanger Aceh', 'Kopi Tarik Aceh',
    'Kopi Durian Medan', 'Kopi Luwak Arabika', 'Kopi Toraja Sapan', 'Kopi Gayo Wine',
    'Kopi Kintamani Bali', 'Kopi Flores Bajawa', 'Kopi Lampung Robusta', 'Kopi Jahe Rempah',
    'Kopi Kelapa Muda', 'Kopi Alpukat Kocok', 'Es Kopi Cincau', 'Kopi Rempah Nusantara',
    'Espresso Single Origin', 'Americano Dingin', 'Cafe Latte Art', 'Cappuccino Classic',
    'Caramel Macchiato', 'Mochaccino Coklat', 'Affogato Es Krim', 'Cold Brew 12 Jam',
    'Vietnam Drip Susu', 'Dalgona Coffee', 'Kopi Butter Bulletproof', 'Flat White',
    'Kopi Susu Regal', 'Es Kopi Pandan', 'Kopi Aren Oat Milk',
  ],

  'Teh & Minuman Segar': [
    'Es Teh Manis Jumbo', 'Teh Tarik Malaysia', 'Teh Talua Minang', 'Es Teh Lemon Sereh',
    'Teh Poci Gula Batu', 'Es Teh Leci', 'Es Teh Peach', 'Thai Tea Original', 'Green Thai Tea',
    'Matcha Latte Es', 'Hojicha Latte', 'Milk Tea Boba Brown Sugar', 'Taro Milk Tea',
    'Cheese Tea Oolong', 'Lemon Tea Hangat', 'Teh Rosella Merah', 'Teh Bunga Telang Lemon',
    'Teh Chamomile Madu', 'Wedang Sereh Madu', 'Es Jeruk Peras', 'Es Jeruk Nipis Selasih',
    'Es Lemon Madu Mint', 'Jus Alpukat Coklat', 'Jus Mangga Kental', 'Jus Strawberry Yogurt',
    'Jus Jambu Merah', 'Jus Sirsak Susu', 'Jus Melon Segar', 'Jus Semangka Dingin',
    'Jus Tomat Wortel', 'Jus Buah Naga Pisang', 'Jus Kurma Susu', 'Smoothies Mangga Yogurt',
    'Smoothies Pisang Oat', 'Milkshake Coklat Oreo', 'Milkshake Vanilla', 'Milkshake Strawberry',
    'Korean Strawberry Milk', 'Susu Kurma Hangat', 'Es Susu Coklat Regal', 'Es Milo Dinosaurus',
    'Es Mojito Lemon Mint', 'Virgin Mojito Strawberry', 'Es Soda Gembira', 'Es Sirup Squash Jeruk',
    'Infused Water Lemon Timun', 'Es Yakult Leci', 'Es Yakult Jeruk', 'Blue Ocean Soda',
    'Es Buah Naga Selasih', 'Air Kelapa Jeruk Nipis', 'Es Markisa Medan', 'Es Kuwini Harum',
  ],

  'Internasional': [
    'Spaghetti Bolognese', 'Spaghetti Carbonara', 'Spaghetti Aglio Olio', 'Fettuccine Alfredo',
    'Lasagna Panggang Keju', 'Penne Arrabbiata', 'Ravioli Keju', 'Gnocchi Saus Tomat',
    'Pizza Margherita', 'Pizza Pepperoni', 'Pizza Teflon Rumahan', 'Calzone Isi Daging',
    'Risotto Jamur', 'Bruschetta Tomat Basil', 'Panini Sandwich', 'Beef Steak Saus Mushroom',
    'Sirloin Steak Lada Hitam', 'Tenderloin Steak Saus BBQ', 'Chicken Steak Krispi',
    'Salisbury Steak', 'Beef Burger Keju', 'Chicken Burger Krispi', 'Hotdog Sosis Panggang',
    'Club Sandwich', 'Fish Burger Tartar', 'Mac and Cheese Panggang', 'Mashed Potato Gravy',
    'Chicken Cordon Bleu', 'Chicken Parmigiana', 'Roast Chicken Rosemary', 'Grilled Salmon Lemon Butter',
    'Beef Wellington', 'Shepherd\'s Pie', 'Quiche Lorraine', 'Omelette Du Fromage',
    'Caesar Salad Ayam', 'Coleslaw Segar', 'Sushi Roll California', 'Sushi Salmon Nigiri',
    'Sashimi Salmon Tuna', 'Ramen Shoyu Ayam', 'Ramen Miso Pedas', 'Udon Kuah Dashi',
    'Yakisoba Goreng', 'Chicken Katsu Curry', 'Beef Teriyaki Don', 'Gyudon Yoshinoya Style',
    'Oyakodon Telur Ayam', 'Katsudon Krispi', 'Onigiri Salmon', 'Tempura Udang Krispi',
    'Takoyaki Gurita', 'Okonomiyaki Osaka', 'Gyoza Ayam Kukus', 'Chicken Karaage',
    'Ebi Furai Udang', 'Shabu-Shabu Kuah Kombu', 'Sukiyaki Daging Sapi', 'Miso Soup Tofu',
    'Chawanmushi Telur Kukus', 'Kimchi Jjigae', 'Tteokbokki Pedas Manis', 'Korean Fried Chicken Yangnyeom',
    'Bulgogi Sapi Bawang', 'Bibimbap Sayur Telur', 'Japchae Soun Korea', 'Kimbap Isi Komplit',
    'Samgyeopsal Panggang', 'Sundubu Jjigae Tahu', 'Rabokki Mie Tteok', 'Corndog Kentang Mozarella',
    'Dakgalbi Ayam Pedas', 'Ayam Goreng Korea Madu Bawang', 'Kung Pao Chicken', 'Sapo Tahu Seafood',
    'Fuyunghai Saus Asam Manis', 'Koloke Ayam Asam Manis', 'Nasi Hainan Ayam Rebus', 'Dimsum Siomay Ayam',
    'Hakau Udang', 'Xiao Long Bao', 'Bakpao Isi Ayam', 'Chasio Ayam Panggang Madu',
    'Bebek Panggang Hongkong', 'Nasi Tim Hongkong', 'Tom Yum Goong Seafood', 'Tom Kha Gai Ayam',
    'Pad Thai Udang', 'Thai Basil Chicken', 'Green Curry Ayam Thailand', 'Som Tam Salad Pepaya',
    'Thai Mango Salad', 'Chicken Satay Thai Peanut', 'Nasi Goreng Nanas Thailand', 'Butter Chicken India',
    'Chicken Tikka Masala', 'Chicken Biryani India', 'Dal Tadka Lentil', 'Naan Bread Butter Garlic',
    'Samosa India', 'Roti Canai Kari Ayam', 'Nasi Lemak Malaysia', 'Laksa Singapura',
    'Chilli Crab Singapura', 'Hainanese Chicken Rice', 'Kebab Turki Daging Sapi', 'Shawarma Ayam',
    'Hummus Kacang Arab', 'Falafel Goreng', 'Nasi Kabsah Arab', 'Nasi Bukhari Ayam',
    'Shakshuka Telur Tomat', 'Baklava Kacang Madu', 'Burrito Daging Sapi', 'Taco Meksiko Ayam',
    'Quesadilla Keju Ayam', 'Nachos Beef Melted', 'Enchilada Ayam', 'Guacamole Alpukat',
    'Paella Seafood Spanyol', 'Tortilla Espanola', 'Croque Monsieur', 'Ratatouille Sayur',
    'Coq au Vin Ayam', 'Beef Bourguignon', 'Poutine Kentang Keju', 'Chicken Pot Pie',
  ],

  'Rumahan Sederhana': [
    'Telur Ceplok Kecap', 'Telur Dadar Bawang', 'Telur Orak-Arik Sosis', 'Telur Mata Sapi Sambal',
    'Tumis Sosis Kecap Pedas', 'Sosis Bakar Saus BBQ', 'Nugget Ayam Goreng', 'Nugget Tempe Homemade',
    'Nasi Putih Ayam Suwir Kecap', 'Nasi Telur Ponorogo', 'Nasi Mentai Salmon Rumahan', 'Nasi Mentai Ayam Krispi',
    'Indomie Goreng Telur Ceplok', 'Indomie Kuah Keju Pedas', 'Mie Instan Carbonara', 'Magelangan Nasi Mie',
    'Tumis Bakso Sayuran', 'Bakso Goreng Saus Tiram', 'Sarden Kaleng Tumis Pedas', 'Kornet Tumis Buncis',
    'Ayam Suwir Kecap Simple', 'Ayam Goreng Ungkep Sederhana', 'Ikan Goreng Sambal Kecap', 'Telur Puyuh Kecap',
    'Tumis Toge Tahu Simple', 'Cah Sawi Bawang Putih', 'Sup Sayur Simpel Anak Kos', 'Sup Telur Tomat',
    'Omelet Mie Sayur', 'Nasi Goreng Bumbu Instan Upgrade', 'Nasi Goreng Terasi Simple', 'Nasi Goreng Margarin',
    'Roti Tawar Gulung Sosis', 'Roti Kukus Coklat Simple', 'Pisang Kukus Kelapa', 'Kentang Goreng Rumahan',
    'Perkedel Tahu Simple', 'Tahu Goreng Sambal Kecap', 'Tempe Goreng Bawang', 'Tumis Kacang Panjang Simple',
    'Sayur Bening Katuk Jagung', 'Sup Makaroni Sosis Anak', 'Bola-Bola Nasi Isi Keju', 'Nasi Bakar Teflon Simple',
    'Ayam Fillet Saus Tiram Simple', 'Chicken Wings Madu Teflon', 'Ayam Pop Rice Cooker', 'Nasi Ayam KFC Rice Cooker',
    'Telur Kukus Jepang Simple', 'Puding Susu 3 Bahan', 'Es Lilin Coklat Homemade', 'Pisang Bakar Coklat Keju Teflon',
    'Roti Bakar Teflon Srikaya', 'Sandwich Isi Telur Simple', 'Salad Buah Simple Mayo', 'Jasuke Rumahan',
    'Dimsum Ayam Rice Cooker', 'Sempol Ayam Teflon', 'Cireng Nasi Sisa', 'Donat Tanpa Telur Simple',
  ],
}

export const ALL_DISHES: Dish[] = Object.entries(RAW).flatMap(([kategori, items]) =>
  items.map((nama) => ({ nama, kategori }))
)

export const CATEGORIES: string[] = Object.keys(RAW)

export const TOTAL_DISHES = ALL_DISHES.length
